### ISSUE TITLE
Multiple creatives for the same line-item

### ISSUE THREAD

**Issue by ericsson66** [kmjennison/dfp-prebid-setup#13]
Hi and many thanks for this great tool! I was able to make it work even I don't know ANYTHING about Python :)

I've a suggestion though: would it be possible to add a parameter to specify the number of creatives to attach to each line-items?

For now I see only one creative per line-item, and in some occurrences the second ad doesn't serve any creative if the same partner wins with the same bid price on two different ad-slots.

Thanks
Eric

**Comment by kmjennison** [comment]
Great, I'm glad you've found it helpful!

What you described is definitely a problem. DFP [specifies](https://support.google.com/dfp_sb/answer/82245?hl=en) that "Each of a line item's assigned creatives can only serve once per page". That's why Prebid's [ad ops instructions](http://prebid.org/adops/step-by-step.html#step-4-duplicate-creatives) say to duplicate the creatives to match the number of ad units on a page.

I'll try to fix this in the next week or so.

**Comment by ericsson66** [comment]
Thanks for your prompt reply,

Yes indeed ;) For now, as I have only this new partner, I will check which line-items are most used and duplicate the creatives manually... Unless I find a better workaround in DFP...

Best,
Eric

**Comment by kmjennison** [comment]
@ericsson66 Also, heads up that this code currently uses the same creative for every line item for a bidder. So, I'd expect DFP to serve only one creative if that bidder wins more than one bid *regardless* of bid price.

**Comment by ericsson66** [comment]
@kmjennison Yeah, I see what you mean.

I set up 3 new creatives that I attached to each line item though DFP, so it should cover everything.

Anyway, this feature of choosing how many creatives to create and attach to each line-item would be a big plus.

Best

**Comment by kmjennison** [comment]
Fixed in #14. Thanks for the issue!
