### ISSUE TITLE
Key-values and/or

### ISSUE THREAD

**Issue by Sirsly73** [kmjennison/dfp-prebid-setup#77]
Hello,
in my last installation (2018) in the field key-values i have "OR" (like this: https://ibb.co/vQR4783) but now there is "AND" (like this: https://ibb.co/T2B0Bzf).
I haven't see anything to modify in settings.py
Am I doing something wrong?
Thanks

**Comment by kmjennison** [comment]
The key-values logic *should* be "and" so that it matches only the one line item that has that bidder name and price. That looks correct.

I'm not sure why your previous line items use "or", but be careful with that setting: it will match anything with that bidder name, even at another price, so I wouldn't expect the correct line item to win if you have more than one bidder.
